version: "2"

services:
  db:
    image: postgres
    env_file: .env

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"

  app:
    tty: true
    stdin_open: true
    build: .
    env_file: .env
    command: rails server -b 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3000"
    links:
      - db
      - redis
